services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=bookstack
      - POSTGRES_PASSWORD=password

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  php_redis_admin:
    image: erikdubbelboer/phpredisadmin:latest
    environment:
      - REDIS_1_HOST=redis
    ports:
      - 8081:80
