# Generated by Django 5.0.3 on 2024-04-12 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_book_notes_alter_book_price_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="book",
            name="ownership_type",
        ),
        migrations.CreateModel(
            name="UserLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ownership_type",
                    models.CharField(
                        choices=[
                            ("E-Book", "E Book"),
                            ("Audio Book", "Audio Book"),
                            ("Owned Physical Book", "Owned Physical Book"),
                            ("Borrowed Book", "Borrowed Book"),
                        ],
                        default="Owned Physical Book",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="books.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
