# Generated by Django 5.0.3 on 2024-05-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_remove_userlibrary_user_profile_userlibrary_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlibrary",
            name="state",
            field=models.CharField(default="to_be_read"),
        ),
    ]
