# Generated by Django 5.0.3 on 2024-05-20 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0009_rename_userlibrary_profilelibrary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profilelibrary",
            options={"managed": False},
        ),
    ]
