# Generated by Django 5.0.3 on 2024-05-20 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0010_alter_profilelibrary_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"managed": False},
        ),
        migrations.AlterModelTable(
            name="profilelibrary",
            table="ProfileLibrary",
        ),
    ]
