version: 2.1

jobs:
  lint:
    docker:
      - image: pyfound/black:22.12.0
    steps:
      - checkout
      - run: black --check .
  test:
    environment:
      PIPENV_VENV_IN_PROJECT: 1
      DB_USER: postgres
      DB_HOST: localhost
      DB_PASSWORD: password
      REDIS_URL: "redis://localhost:6379"
      ENCRYPTION_KEY: "ZmFrZWZha2VmYWtlZmFrZWZha2VmYWtlZmFrZWZha2U="
    docker:
      - image: cimg/python:3.12
      - image: cimg/redis:7.4
      - image: cimg/postgres:15.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - run: |
          pip install --user pipenv
          pipenv install
          pipenv run python manage.py test

workflows:
  cx-pipeline:
    jobs:
      - lint
      - test
