version: 2.1

jobs:
  lint:
    docker:
      - image: pyfound/black:22.12.0
    steps:
      - checkout
      - run: black --check .
  test:
    environment:
      PIPENV_VENV_IN_PROJECT: 1
    docker:
      - image: cimg/python:3.12
      - image: cimg/redis:7.4
      - image: cimg/postgres:15.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - run: |
          cp .env.template .env
          pip install --user pipenv
          pipenv install
          pipenv run python manage.py test

workflows:
  cx-pipeline:
    jobs:
      - lint
      - test
