apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

configMapGenerator:
  - name: bookstack-app-config
    envs:
      - app.env

secretGenerator:
  - name: bookstack-app-secrets
    envs:
      - app-secrets.env

resources:
  - ../base
  - ingress.yaml
