apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack-app
  labels:
    app: bookstack-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstack-app
  template:
    metadata:
      labels:
        app: bookstack-app
    spec:
      containers:
        - name: bookstack
          image: bookstack:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: bookstack-app-config
            - secretRef:
                name: bookstack-app-secrets
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
      initContainers:
        - name: init-migrations
          image: bookstack:latest
          imagePullPolicy: Always
          command: ["pipenv", "run", "python", "manage.py", "migrate"]
          envFrom:
            - configMapRef:
                name: bookstack-app-config
            - secretRef:
                name: bookstack-app-secrets
